/**
 * Phase 3D-1 — cross-language parity.
 *
 * Covers required tests Q (fixture copies identical) and R (all golden scenarios match
 * Python exactly).
 *
 * Two independent layers, deliberately:
 *
 *   1. COMMITTED GOLDENS. `custom_mix_golden_results.json` was generated by running
 *      `pipeline/custom_mix_selector.py`. The TypeScript selector is compared against it on
 *      every run, with no Python needed. Nothing here ever rewrites that file — a golden
 *      that a test can update is not a golden.
 *
 *   2. LIVE PYTHON. When `python3` is available, the Python selector is executed against
 *      the same fixture and compared directly, which also proves the committed goldens have
 *      not drifted from the implementation they claim to describe.
 *
 * Python is spawned ONLY here. No production module imports `child_process`, and none reads
 * anything from `pipeline/`.
 */

import assert from "node:assert/strict";
import test from "node:test";
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { selectCustomMix } from "../_lib/custom-mix-selector.js";
import { productionEditorialDuplicateGuard } from "../_lib/editorial-duplicate-guard.js";
import {
  type EditorialDuplicateGuard,
  type MixCandidate,
  type MixSelectionResult,
} from "../_lib/custom-mix-types.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = resolve(HERE, "..", "_fixtures");

/**
 * Walk up for the repository root — the directory holding `pipeline/custom_mix_selector.py`.
 * Resolving `../..` would be correct for the source layout only, and would point somewhere
 * meaningless when the suite runs from a compiled output directory.
 */
function findPipelineDir(): string {
  let current = HERE;
  for (let depth = 0; depth < 8; depth += 1) {
    const candidate = join(current, "pipeline");
    if (existsSync(join(candidate, "custom_mix_selector.py"))) return candidate;
    const parent = dirname(current);
    if (parent === current) break;
    current = parent;
  }
  return join(resolve(HERE, "..", ".."), "pipeline"); // reported as missing below
}

const PIPELINE_DIR = findPipelineDir();
const PYTHON_FIXTURE = join(PIPELINE_DIR, "fixtures", "custom_mix_candidates.json");

type Golden = {
  fixtureSha256: string;
  date: string;
  scenarios: {
    name: string;
    input: {
      candidateIds: string[];
      regions: string[];
      topics: string[];
      size: number;
      selectorVersion: number;
    };
    result: MixSelectionResult;
  }[];
};

const fixtureBytes = readFileSync(join(FIXTURE_DIR, "custom_mix_candidates.json"));
const golden = JSON.parse(
  readFileSync(join(FIXTURE_DIR, "custom_mix_golden_results.json"), "utf8"),
) as Golden;
const candidatesById = new Map(
  (JSON.parse(fixtureBytes.toString("utf8")) as { candidates: MixCandidate[] }).candidates.map(
    (c) => [c.id, c],
  ),
);

function poolFor(ids: string[]): MixCandidate[] {
  return ids.map((id) => {
    const candidate = candidatesById.get(id);
    assert.ok(candidate, `fixture is missing candidate ${id}`);
    return structuredClone(candidate);
  });
}

function runTypeScript(
  scenario: Golden["scenarios"][number],
  // The PRODUCTION guard by default: parity must be proven on the path that ships.
  guard: EditorialDuplicateGuard = productionEditorialDuplicateGuard,
): MixSelectionResult {
  return selectCustomMix({
    candidates: poolFor(scenario.input.candidateIds),
    date: golden.date,
    regions: scenario.input.regions,
    topics: scenario.input.topics,
    size: scenario.input.size,
    selectorVersion: scenario.input.selectorVersion,
    editorialDuplicateGuard: guard,
  });
}

/**
 * Round-trip through JSON so the comparison is value-based.
 *
 * This is the ONLY normalisation applied, and it is not a numeric tolerance: Python writes
 * `92.0` where JavaScript writes `92`, but both parse to the same IEEE-754 double, so
 * `deepStrictEqual` over parsed values compares the numbers exactly. No epsilon is used
 * anywhere — a one-ulp difference would still fail.
 */
function normalize(value: unknown): unknown {
  return JSON.parse(JSON.stringify(value));
}

// ── Q. the two fixture copies are identical ───────────────────────────────────────────

test("Q. the api/ and pipeline/ fixture copies are byte-identical", () => {
  assert.ok(existsSync(PYTHON_FIXTURE), `python fixture missing at ${PYTHON_FIXTURE}`);
  const pythonBytes = readFileSync(PYTHON_FIXTURE);
  const apiHash = createHash("sha256").update(fixtureBytes).digest("hex");
  const pythonHash = createHash("sha256").update(pythonBytes).digest("hex");

  assert.equal(apiHash, pythonHash, "the fixture copies have diverged");
  assert.equal(
    apiHash,
    golden.fixtureSha256,
    "the golden results were generated from a different fixture",
  );
});

// ── R. every golden scenario matches ──────────────────────────────────────────────────

test("R. all eight golden scenarios match the committed Python output exactly", () => {
  assert.equal(golden.scenarios.length, 8, "expected eight golden scenarios");
  const names = golden.scenarios.map((s) => s.name).sort();
  assert.deepEqual(names, [
    "A_japan_only_five_or_more",
    "B_japan_only_exactly_three",
    "C_japan_only_duplicate_event",
    "D_japan_and_us",
    "E_japan_and_tech",
    "F_reordered_inputs",
    "G_shortage_below_five",
    "H_fallback_duplicates_regional",
  ]);

  for (const scenario of golden.scenarios) {
    const actual = normalize(runTypeScript(scenario)) as MixSelectionResult;
    const expected = scenario.result;

    // Fail on the specific dimension first, so a mismatch is readable.
    assert.deepEqual(actual.selectedIds, expected.selectedIds, `${scenario.name}: selected IDs`);
    assert.equal(
      actual.metadata.mixIdentity,
      expected.metadata.mixIdentity,
      `${scenario.name}: mix identity`,
    );
    assert.deepEqual(actual.metadata, expected.metadata, `${scenario.name}: metadata`);
    assert.deepEqual(
      actual.candidateLogs,
      expected.candidateLogs,
      `${scenario.name}: candidate logs`,
    );
    // …then the whole structure, so nothing outside those fields can drift either.
    assert.deepEqual(actual, expected, `${scenario.name}: full result`);
  }
});

test("R2. every golden scenario carries the required reporting fields", () => {
  for (const scenario of golden.scenarios) {
    const meta = scenario.result.metadata;
    for (const field of [
      "mixIdentity",
      "selectedRegionStories",
      "fallbackSlots",
      "fallbackReason",
      "finalRegionMix",
      "qualifyingRegionCandidates",
      "regionalCandidatesAfterDedup",
    ] as const) {
      assert.ok(field in meta, `${scenario.name} is missing metadata.${field}`);
    }
    assert.ok(Array.isArray(scenario.result.selectedIds));
    assert.ok(scenario.result.candidateLogs.every((log) => "selectionPhase" in log));
  }
});

test("R3. the golden file records no wall-clock timestamp", () => {
  const serialized = JSON.stringify(golden);
  assert.ok(
    !/"(generatedAt|timestamp|createdAt|ranAt)"/.test(serialized),
    "the golden file records a wall-clock time and will drift",
  );
  // A bare ISO datetime would be equally bad. Fixture publishedAt values live in the
  // candidate fixture, not here.
  assert.ok(!/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(serialized));
});

test("R4. rejected duplicates and their reasons match the golden output", () => {
  const scenario = golden.scenarios.find((s) => s.name === "H_fallback_duplicates_regional");
  assert.ok(scenario);
  const actual = runTypeScript(scenario);
  const rejected = actual.candidateLogs
    .filter((log) => (log.rejectionReason ?? "").startsWith("duplicate "))
    .map((log) => [log.id, log.rejectionReason]);
  const expected = scenario.result.candidateLogs
    .filter((log) => (log.rejectionReason ?? "").startsWith("duplicate "))
    .map((log) => [log.id, log.rejectionReason]);
  assert.deepEqual(rejected, expected);
  assert.ok(rejected.length > 0, "this scenario should reject at least one duplicate");
});

// ── live Python comparison ────────────────────────────────────────────────────────────

/** Runs the Python selector for every golden scenario, plus a duplicate-guard call count. */
function runPython(): {
  ok: boolean;
  reason?: string;
  results?: Record<string, MixSelectionResult>;
  guardCalls?: Record<string, number>;
} {
  if (!existsSync(PIPELINE_DIR)) return { ok: false, reason: "pipeline/ is not present" };

  const script = `
import json, os, sys
sys.path.insert(0, os.environ["PIPELINE_DIR"])
import editorial, custom_mix_selector

scenarios = json.loads(os.environ["SCENARIOS"])
fixture = os.path.join(os.environ["PIPELINE_DIR"], "fixtures", "custom_mix_candidates.json")
cands = {c["id"]: c for c in json.load(open(fixture, encoding="utf-8"))["candidates"]}

counts = {}
real = editorial.duplicate_story
state = {"n": 0}
def spy(*a, **k):
    state["n"] += 1
    return real(*a, **k)
custom_mix_selector.duplicate_story = spy

results = {}
for s in scenarios:
    state["n"] = 0
    pool = [json.loads(json.dumps(cands[i])) for i in s["input"]["candidateIds"]]
    results[s["name"]] = custom_mix_selector.select_custom_mix(
        pool, os.environ["DATE"], s["input"]["regions"], s["input"]["topics"],
        s["input"]["size"], s["input"]["selectorVersion"])
    counts[s["name"]] = state["n"]

sys.stdout.write(json.dumps({"results": results, "guardCalls": counts}))
`;

  const proc = spawnSync("python3", ["-c", script], {
    encoding: "utf8",
    env: {
      ...process.env,
      PIPELINE_DIR: PIPELINE_DIR,
      DATE: golden.date,
      SCENARIOS: JSON.stringify(golden.scenarios.map((s) => ({ name: s.name, input: s.input }))),
    },
    maxBuffer: 32 * 1_024 * 1_024,
  });

  if (proc.error) return { ok: false, reason: `python3 unavailable: ${proc.error.message}` };
  if (proc.status !== 0) {
    return { ok: false, reason: `python exited ${proc.status}: ${(proc.stderr || "").slice(-400)}` };
  }
  const parsed = JSON.parse(proc.stdout) as {
    results: Record<string, MixSelectionResult>;
    guardCalls: Record<string, number>;
  };
  return { ok: true, results: parsed.results, guardCalls: parsed.guardCalls };
}

test("R5. the LIVE Python selector and the TypeScript port agree on every scenario", (t) => {
  const python = runPython();
  if (!python.ok) {
    // Never silently pass: say exactly why the strongest check did not run.
    t.skip(`live Python comparison skipped — ${python.reason}`);
    return;
  }

  for (const scenario of golden.scenarios) {
    const expected = normalize(python.results?.[scenario.name]);
    const actual = normalize(runTypeScript(scenario));
    assert.deepEqual(actual, expected, `${scenario.name}: TypeScript differs from live Python`);
    // And the committed golden still describes what Python actually does today.
    assert.deepEqual(
      expected,
      normalize(scenario.result),
      `${scenario.name}: the committed golden has drifted from live Python`,
    );
  }
});

test("R6. the editorial duplicate seam is reached the same number of times as in Python", (t) => {
  const python = runPython();
  if (!python.ok) {
    t.skip(`live Python comparison skipped — ${python.reason}`);
    return;
  }

  let totalPython = 0;
  let totalTypeScript = 0;
  let totalFired = 0;
  for (const scenario of golden.scenarios) {
    let calls = 0;
    runTypeScript(scenario, (a, b) => {
      calls += 1;
      // Wraps the REAL guard, so the call sequence is the production one.
      const decision = productionEditorialDuplicateGuard(a, b);
      if (decision.duplicate) totalFired += 1;
      return decision;
    });
    const pythonCalls = python.guardCalls?.[scenario.name] ?? -1;
    assert.equal(
      calls,
      pythonCalls,
      `${scenario.name}: guard consulted ${calls} times in TS vs ${pythonCalls} in Python`,
    );
    totalTypeScript += calls;
    totalPython += pythonCalls;
  }

  assert.equal(totalTypeScript, totalPython);
  assert.equal(totalTypeScript, 392, "the guard call count changed unexpectedly");
  assert.ok(totalPython > 0, "the seam was never reached — the comparison proves nothing");
  assert.equal(
    totalFired,
    0,
    "the real guard now fires on the base fixture — the goldens would need regenerating",
  );
});

// ── boundary checks ───────────────────────────────────────────────────────────────────

/** Drop block comments and whole-line `//` comments, so the scan measures CODE, not prose. */
function stripComments(source: string): string {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .split("\n")
    .filter((line) => {
      const trimmed = line.trim();
      return !trimmed.startsWith("//") && !trimmed.startsWith("*");
    })
    .join("\n");
}

test("no production selector module reads a file or spawns a process", () => {
  for (const relative of [
    "custom-mix-types.ts",
    "custom-mix-identity.ts",
    "custom-mix-selector.ts",
  ]) {
    const source = stripComments(readFileSync(join(HERE, "..", "_lib", relative), "utf8"));
    for (const needle of [
      "readFileSync",
      "readFile",
      "child_process",
      "spawn",
      "execFile",
      "process.env",
      "pipeline/",
      "latest.json",
      "editions/",
      "mix-pool",
      "fetch(",
      "console.",
    ]) {
      assert.ok(!source.includes(needle), `${relative} references ${needle}`);
    }
  }
});

test("the selector is not wired into any API route yet", () => {
  for (const relative of ["edition.ts", "_lib/runtime-factory.ts", "_lib/vercel-runtime.ts"]) {
    const source = readFileSync(join(HERE, "..", relative), "utf8");
    assert.ok(
      !source.includes("custom-mix-selector"),
      `${relative} already imports the selector — /api/edition must stay disconnected`,
    );
  }
  const edition = readFileSync(join(HERE, "..", "edition.ts"), "utf8");
  assert.ok(edition.includes("selector_not_connected"));
});
